version: '3.8'
services:
  gui:
    build:
      context: .
      dockerfile: ./gui/Dockerfile
    environment:
      - PORT=8080
      - REPO_HOST=http://api:8081
      - REPO_API_KEY=foobar
    ports:
      - 8080:8080
    links:
      - api
      - pki_c
      - pki_d
  
  api:
    build:
      context: ./api
    environment:
      - DEBUG=true
      - PORT=8081
      - API_KEY=foobar
 
  pki_a:
    image: ghcr.io/wirepact/k8s-pki:2.3.5
    environment:
      - DEBUG=true
      - PORT=8082
      - LOCAL=true
      - API_KEY=pki_a
    ports:
      - 8082:8082
 
  pki_b:
    image: ghcr.io/wirepact/k8s-pki:2.3.5
    environment:
      - DEBUG=true
      - PORT=8083
      - LOCAL=true
      - API_KEY=pki_b
    ports:
      - 8083:8083
  
  pki_c:
    image: ghcr.io/wirepact/k8s-pki:2.3.5
    environment:
      - DEBUG=true
      - PORT=8080
      - LOCAL=true
  
  pki_d:
    image: ghcr.io/wirepact/k8s-pki:2.3.5
    environment:
      - DEBUG=true
      - PORT=8080
      - LOCAL=true
