[package]
name = "k8s-contract-repository"
version = "0.0.0-development"
edition = "2021"

[dependencies]
clap = { version = "3.2.16", features = ["derive", "env"] }
custom_error = "1.9.2"
env_logger = "0.9.0"
hex = "0.4.3"
itertools = "0.10.3"
k8s-openapi = { version = "0.15.0", features = ["v1_22"] }
kube = "0.74.0"
log = "0.4.17"
openssl = "0.10.41"
openssl-sys = "0.9.75"
prost = "0.12.3"
prost-types = "0.12.3"
sha2 = "0.10.2"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread", "fs", "signal"] }
tonic = { version = "0.11.0", features = ["tls", "tls-roots", "tls-roots-common"] }
tonic-types = "0.11.0"
tonic-web = "0.11.0"

[dev-dependencies]
base64 = "0.13.0"
serial_test = "0.8.0"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tonic-build = "0.11.0"
